config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get 'cart_items/create'
    get 'cart_items/update'
    get 'cart_items/destroy'
    get 'carts/show'
    get 'static_pages/about'
    get 'static_pages/home'
    post '/rate' => 'rater#create', :as => 'rate'
    resources :consumables, only: [:index, :show]
    resources :users
    resources :ratings
    resources :categories
    resources :carts
    resources :cart_items

    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
  	resources :users
    resources :categories do
      member do
        get :of_categories
      end
    end
    namespace :admin do
      resources :consumables, except: :show
      resources :users
    end
  end
end

app/models/consumable.rb
class Consumable < ActiveRecord::Base
  scope :not_discarded, -> { where(discarded_at: nil)}

  has_many :cart_items
  has_many :category_consumables, dependent: :delete_all
  has_many :categories, through: :category_consumables, dependent: :delete_all
  has_many :ratings

  validates :name, presence: true,
                   length: {minimum: 1, maximum: 100}
  # validates :picture, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  scope :by_name, -> (keyword) {where('name LIKE ?', "%#{keyword}%")}
  # default_scope { where(active: true)}

  mount_uploader :pictures, PictureUploader
end

app/controllers/admin/consumables_controller.rb
class Admin::ConsumablesController < ApplicationController

  def index
    @categories = Category.all
    @cart_item = current_cart.cart_items.new if logged_in?
    @consumables = if params[:term]
      Consumable.by_name(params[:term]).paginate(page: params[:page])
    else
      Consumable.all.paginate(page: params[:page])
    end
  end

  def new
    @consumable = Consumable.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @consumable = Consumable.new(consumable_params)
    @cart_item = current_cart.cart_items.new if logged_in?
    @consumables =
      if params[:term]
        Consumable.by_name(params[:term]).paginate(page: params[:page])
      else
        Consumable.all.paginate(page: params[:page])
      end
      if @consumable.save
        respond_to do |format|
          format.js
        end
      else
        render :index
     end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @consumable.update_attributes(consumable_params)
      respond_to do |format|
        format.js
      end
    else
      render :index
      flash[:danger] = "consumable not created"
    end

  end

  def destroy
    @consumable.discard
    respond_to do |format|
      format.js
    end
  end

  private

  def find_consumables
    consumables = Consumable.all
    @consumables = consumables.not_discarded.paginate(page: params[:page], per_page: 10)
  end

  def find_consumable
    @consumable = Consumable.find_by(id: params[:id])
    unless @consumable
      redirect_to root_path
      flash[:danger] = "Consumable not found"
    end
  end

  def consumable_params
    params.require(:consumable).permit(:name, :description, :price, :quantity, :pictures)
  end
end

app/controllers/consumables_controller.rb
class ConsumablesController < ApplicationController
  include ConsumablesHelper

  before_action :find_consumable, except: [:index, :new, :create]
  before_action :find_consumables, except: [:show]
  skip_before_action :authenticate_user!

  def index
    @categories = Category.all
    @cart_item = current_cart.cart_items.new if logged_in?
    @consumables = if params[:term]
      Consumable.by_name(params[:term]).paginate(page: params[:page])
    else
      Consumable.all.paginate(page: params[:page])
    end
  end

  def show
    @rating = calculate_rate(@consumable.ratings)
  end

  private
  def find_consumables
    consumables = Consumable.all
    @consumables = consumables.not_discarded.paginate(page: params[:page], per_page: 10)
  end

  def find_consumable
    @consumable = Consumable.find_by(id: params[:id])
    unless @consumable
      redirect_to root_path
      flash[:danger] = "Consumable not found"
    end
  end

  def consumable_params
    params.require(:consumable).permit(:name, :description, :price, :quantity, pictures: [])
  end
end

app/helpers/consumables_helper.rb
module ConsumablesHelper
  def calculate_rate(ratings)
    counts = ratings.count
    rating = counts == 0 ? 0 : (ratings.sum(:rating) / counts)
  end
end

app/views/admin/consumables/_consumables.html.erb
<% @consumables.each do |consumable| %>
  <div class="col-3">
    <div class="card">
      <%# image_tag consumable.picture.preview(resize_to_limit: [100, 100]) %>
      <div class="card-body">
        <p class="card-text"><%= t(".name") %>:  <%= consumable.name %></p>
        <p class="card-text"><%= t(".rating") %>: <span style="color: red"><%= consumable.rate_average %></span></p>
        <p class="card-text"><%= t(".quantity") %>:<%= consumable.quantity %>  </p>
          <div class="thumb thumb-custom">
            <%= image_tag consumable.pictures.url, class: "img-fluid img-consumable-home" %>
          </div>
        <% if logged_in? %>
          <%= form_for @cart_item, remote: true do |f| %>
            <h4 class="text-right">Price: <span style="color: green"><%= number_to_currency consumable.price %></span></h4>
            <div class="input-group">
              <%= f.number_field :quantity, value: 0, class: "form-control", min: 1 %>
              <div class="input-group-btn">
                <%= f.hidden_field :unit_price, value: consumable.price %>
                <%= f.hidden_field :consumable_id, value: consumable.id %>
                <%= f.submit "Add to Cart", class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
          <small><%= link_to t(".edit"), edit_admin_consumable_path(consumable), remote: true %></small>
          <small>
            <%= link_to t(".delete"), consumable,
                                  method: :delete,
                                  remote: true,
                                  data: {confirm: "Are you sure?"}
            %>
          </small>
        <% end %>
        <small><%= link_to t(".show"), consumable%></small>
      </div>
    </div>
  </div>
<% end %>
<%= will_paginate @consumables%>

app/views/admin/consumables/_edit.html.erb
<div
  id="consumable_modal_edit"
  class="modal fade bd-example-modal-lg"
  aria-hidden="true"
  aria-labelledby="myLargeModalLabel"
  role="dialog"
  tabindex="-1"
>
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5>Edit consumable</h5>
      </div>

      <div class="modal-body">
        <%= form_for @consumable, remote: true do |f| %>
          <%# render "shared/error_messages", object: f.object %> 
          
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.label :picture %>
          <%= f.file_field :picture, multiple: true, direct_upload: true, class: "form-control" %>

          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control" %>

          <%= f.label :price %>
          <%= f.number_field :price, class: "form-control" %>

          <%= f.label :quantity %>
          <%= f.number_field :quantity, class: "form-control" %>

          <%= f.submit "Update consumable", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/consumables/_new.html.erb
<div
  id="consumable_modal_new"
  class="modal fade bd-example-modal-lg"
  aria-hidden="true"
  aria-labelledby="myLargeModalLabel"
  role="dialog"
  tabindex="-1"
>
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5>Add new consumable</h5>
      </div>

      <div class="modal-body">
        <%= form_for [:admin, @consumable], remote: true do |f| %>
          <%# render "shared/error_messages", object: f.object %>

          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.label :pictures %>
          <%= f.file_field :pictures, class: "form-control" %>

          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control" %>

          <%= f.label :price %>
          <%= f.number_field :price, class: "form-control" %>

          <%= f.label :quantity %>
          <%= f.number_field :quantity, class: "form-control" %>

          <%= f.submit "Add new consumable", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/consumables/create.js.erb
$("#consumables_list").html("<%= j render 'consumables/consumables' %>");
$("#consumable_modal_new").modal("hide");
$(".modal-backdrop").fadeOut("fast");

app/views/admin/consumables/destroy.js.erb
$("#consumables_list").html("<%= j render 'admin/consumables/consumables' %>");

app/views/admin/consumables/edit.js.erb
$("#consumable_modal").html("<%= j render 'admin/consumables/edit' %>");
$("#consumable_modal_edit").modal("show");
if (<%=  @consumable.errors.present?  %>) {
  $("#myModalBuyRequest").on("click", function () {
      $(".modal-backdrop").fadeOut("fast");
  });
}

app/views/admin/consumables/index.html.erb
<div class="admin-consumable-screen">
  <div class="box-header"></div>
  <%= form_tag(consumables_path, method: :get) do %>
    <%= text_field_tag :term %>
    <%= submit_tag t(".search") %>
  <% end %>
  <% @categories.each do |category| %>
  <%= link_to category.category, category %>
  <% end %>
  <div class="container">
    <% if logged_in? %>
      <div>
        <%= link_to t(".add consumable"), new_admin_consumable_path, class: "btn btn-primary", remote: true %>
      </div>
    <% end %>
    <div class="row" id="consumables_list">
      <%= render "consumables" %>
    </div>
  </div>
  <div id="consumable_modal"></div>
</div>

app/views/admin/consumables/new.js.erb
$("#consumable_modal").html("<%= j render 'admin/consumables/new' %>");
$("#consumable_modal_new").modal("show");
if (<%=  @consumable.errors.present?  %>) {
  $("#myModalBuyRequest").on("click", function () {
      $(".modal-backdrop").fadeOut("fast");
  });
}

app/views/admin/consumables/show.html.erb
<div class="box-header"></div>
  <div class="col-3">
    <div class="card">
      <%# image_tag consumable.picture.preview(resize_to_limit: [100, 100]) %>
      <div class="card-body">
        <p class="card-text"><%= t(".name") %>: <%= @consumable.name %></p>
        <p class="card-text"><%= t(".price") %>: <%= @consumable.price %></p>
        <p class="card-text"><%= t(".out of stock") %></p>
      </div>
    </div>
  </div>
<h3> <%=t(".rating") %>:<span style="color: red"><%= @rating %></span> </h3>
<%= form_for (Rating.new) do |f| %>
  <%= f.hidden_field :consumable_id, value: @consumable.id %>
  <%= f.text_field :rating %>
  <%= f.submit t(".confirmation") %>
<% end %>

app/views/admin/consumables/update.js.erb
$("#consumables_list").html("<%= j render 'admin/consumables/consumables' %>");
$("#consumable_modal_edit").modal("hide");
$(".modal-backdrop").fadeOut("fast");