config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get 'cart_items/create'
    get 'cart_items/update'
    get 'cart_items/destroy'
    get 'carts/show'
    get 'static_pages/about'
    get 'static_pages/home'
    post '/rate' => 'rater#create', :as => 'rate'
    resources :consumables, only: [:index, :show]
    resources :users
    resources :ratings
    resources :categories
    resources :carts
    resources :cart_items

    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
  	resources :users
    resources :categories do
      member do
        get :of_categories
      end
    end
    namespace :admin do
      resources :consumables, except: :show
      resources :users
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_consumables
  has_many :consumables, through: :category_consumables

 # validates :category, presence :true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :of_categories]
  skip_before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def show
  end

  def of_categories
    @title = "of_categories"
    @consumables = @category.of_categories
  end

  private

  def find_category
    @category = Category.find_by(id: params[:id])
    unless @category
      redirect_to root_path
      flash[:danger] = "category not found"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
  <% @categories.each do |category| %>
  <%= link_to category.category, category%>
  <% end %>

app/views/categories/of_categories.html.erb
<% @consumables.each do |consumable| %>
<%= link_to consumable.name, consumable %>
<% end %>

app/views/categories/show.html.erb
 <a href="<%= of_categories_category_path(@category) %>">
  <strong>
    <%= @category.category_consumables.count %>
  </strong>
  consumables
</a>