config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get 'cart_items/create'
    get 'cart_items/update'
    get 'cart_items/destroy'
    get 'carts/show'
    get 'static_pages/about'
    get 'static_pages/home'
    post '/rate' => 'rater#create', :as => 'rate'
    resources :consumables, only: [:index, :show]
    resources :users
    resources :ratings
    resources :categories
    resources :carts
    resources :cart_items

    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    get "/logout", to: "sessions#destroy"
  	resources :users
    resources :categories do
      member do
        get :of_categories
      end
    end
    namespace :admin do
      resources :consumables, except: :show
      resources :users
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  include Discard::Model

  enum status: {ordering: 0,ordered: 1}
  has_many :cart_items
  before_save :update_subtotal

  def subtotal
    cart_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price.to_i) : 0 }.sum
  end
private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  include Discard::Model

  belongs_to :cart
  belongs_to :consumable

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0}

  def unit_price
    if persisted?
      self[:unit_price]
    else
      consumable.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def consumable_present
    if consumable.nil?
      errors.add(:consumable, "is not vali or is not active")
    end
  end
  def cart_present
    if cart.nil?
      errors.add(:cart, "is not a vali order")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_consumables
  has_many :consumables, through: :category_consumables

 # validates :category, presence :true
end

app/models/category_consumable.rb
class CategoryConsumable < ApplicationRecord
  belongs_to :consumable
  belongs_to :category
end

app/models/consumable.rb
class Consumable < ActiveRecord::Base
  scope :not_discarded, -> { where(discarded_at: nil)}

  has_many :cart_items
  has_many :category_consumables, dependent: :delete_all
  has_many :categories, through: :category_consumables, dependent: :delete_all
  has_many :ratings

  validates :name, presence: true,
                   length: {minimum: 1, maximum: 100}
  # validates :picture, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  scope :by_name, -> (keyword) {where('name LIKE ?', "%#{keyword}%")}
  # default_scope { where(active: true)}

  mount_uploader :pictures, PictureUploader
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :consumable
  belongs_to :user
  validates :rating, :inclusion => 1..5

  scope :of_consumable, ->(consumable) { where(consumable_id: consumable.id) }

  class << self
    def calculate_average_rating(ratings)
      (ratings.inject(0) { |sum, n| sum + n } / ratings.count).round(1)
    end
  end
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  include Discard::Model

  belongs_to :user

  validates :name, presence: true, 
                   length: {minimum: 1, maximum: 100}
  validates :picture, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Discard::Model

  has_one :user_profile
  has_many :carts
  has_many :suggestions
  has_many :ratings
  has_many :consumables, through: :ratings
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
    BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @cart_items = current_cart.cart_items
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :logged_in_user, only:[:create, :index]
  skip_before_action :authenticate_user!

  def create
    @rating = current_user.ratings.new(rating_params)
    consumable = @rating.consumable
    if @rating.save
      ratings = Rating.of_consumable(consumable).pluck(:rating)
      avg = Rating.calculate_average_rating(ratings)
      consumable.update(rate_average: avg)
      redirect_to @rating.consumable
    else
      flash[:success] = "rating 1..5"
      redirect_to @rating.consumable
    end
  end

  def index
    @ratings = Rating.all
  end

  private

  def current_user?
    unless @rating.user == current_user
      redirect_to @consumable
    end
  end

  def rating_params
    params.require(:rating).permit(:rating, :consumable_id)
  end

  def find_rating
    @rating = Rating.find_by(id: params[:id])
    unless @rating
      redirect_to root_path
      flash[:danger] = t(".rating not found")
    end
  end

  def logged_in_user
    if current_user.nil?
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = "error"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update]
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @user = User.new
  end

  def index
    @users = User.all.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t(".welcome to Foods and Drinks")
      redirect_to @user
    else
      redirect_to @user
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def find_user
    @user = User.find_by(id: params[:id])
    unless @user
     redirect_to root_path
     flash[:danger] = "User not found"
   end
  end

  def correct_user
    @user = User.find_by(id: params[:id])
    unless @user == current_user
      redirect_to(root_url)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/consumables_helper.rb
module ConsumablesHelper
  def calculate_rate(ratings)
    counts = ratings.count
    rating = counts == 0 ? 0 : (ratings.sum(:rating) / counts)
  end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def authenticate_user!
    unless current_user
      flash[:danger] = t ".must_login"
      redirect_to login_path
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer_top">
    <div class="container">
      <div class="row">
        <div class="col-xl-3 col-md-6 col-lg-3 ">
          <div class="footer_widget">
            <div class="footer_logo">
              <a href="#">
                <%= image_tag "footer_logo.png" %>
              </a>
            </div>
            <p>5th flora, 700/D kings road, green <br> lane New York-1782 <br>
              <a href="#">+10 367 826 2567</a> <br>
              <a href="#">contact@carpenter.com</a>
            </p>
            <div class="socail_links">
              <ul>
                <li>
                  <a href="#">
                    <i class="ti-facebook"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="ti-twitter-alt"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-instagram"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-pinterest"></i>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-youtube-play"></i>
                  </a>
                </li>
              </ul>
            </div>

          </div>
        </div>
        <div class="col-xl-4 col-md-6 col-lg-4 offset-xl-1">
          <div class="footer_widget">
            <h3 class="footer_title">
              Useful Links
            </h3>
            <ul>
              <li><a href="#">Menu</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#"> Blog</a></li>
            </ul>
          </div>
        </div>
        <div class="col-xl-4 col-md-6 col-lg-4">
          <div class="footer_widget">
            <h3 class="footer_title">
              Subscribe
            </h3>
            <form action="#" class="newsletter_form">
              <input type="text" placeholder="Enter your mail">
              <button type="submit">Subscribe</button>
            </form>
            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
              luckily.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to "English", locale:"en" %>
  <%= link_to "Vietnamese", locale:"vi" %>
</footer>

app/views/layouts/_header.html.erb
<!-- header-start -->
<header>
  <div class="header-area ">
    <div id="sticky-header" class="main-header-area">
      <div class="container-fluid p-0">
        <div class="header_bottom_border">
          <div class="row align-items-center no-gutters">
            <div class="col-xl-3 col-lg-2">
              <div class="logo">
                <a href=<%root_path%>>
                <%= link_to root_path do %>
                  <%= image_tag "logo.png" %>
                <% end %>
              </div>
            </div>
            <div class="col-xl-6 col-lg-7">
              <div class="main-menu  d-none d-lg-block">
                <nav>
                  <ul id="navigation">
                    <li><%= link_to 'FnD', root_path, class: "active" %></li>
                    <li><%= link_to 'Menu', consumables_path, class: "active" %></li>
                    <li><a href="#">Book a Table</a></li>
                    <li><%= link_to 'About us', static_pages_about_path, class: "active" %></li>
                  </ul>
                </nav>
              </div>
            </div>
            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
              <div class="say_hello">
                <% unless logged_in? %>
                      <li>
                        <%= link_to t(".sign_up"), signup_path %>
                      </li>
                      <li>
                        <%= link_to t(".login"), login_path %>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to t(".logout"), logout_path, class: "nav-link" %>
                      </li>
                    <% end %>
              </div>
            </div>
            <div class="col-12">
              <div class="mobile_menu d-block d-lg-none"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- header-end -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pr1903FoodAndDrink523</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg.html_safe